version: '3.8'

services:
  # Backend API service
  medivote-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: medivote-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://medivote:medivote@postgres:5432/medivote
      - REDIS_URL=redis://redis:6379
      - BLOCKCHAIN_RPC_URL=http://ganache:8545
      - DEBUG=True
      - CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    depends_on:
      - postgres
      - redis
      - ganache
    volumes:
      - ./backend:/app
      - ./keys:/app/keys
      - backend-uploads:/app/uploads
    networks:
      - medivote-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    container_name: medivote-postgres
    environment:
      - POSTGRES_DB=medivote
      - POSTGRES_USER=medivote
      - POSTGRES_PASSWORD=medivote
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - medivote-network
    restart: unless-stopped

  # Redis for caching and session storage
  redis:
    image: redis:7-alpine
    container_name: medivote-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - medivote-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Ganache blockchain for development
  ganache:
    image: trufflesuite/ganache:latest
    container_name: medivote-ganache
    ports:
      - "8545:8545"
    command: >
      --host 0.0.0.0
      --port 8545
      --networkId 1337
      --accounts 10
      --defaultBalanceEther 100
      --gasLimit 10000000
      --gasPrice 20000000000
      --deterministic
    networks:
      - medivote-network
    restart: unless-stopped

volumes:
  postgres-data:
  redis-data:
  backend-uploads:

networks:
  medivote-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 